# Generated by Django 4.2.15 on 2024-08-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
